### ISSUE TITLE
Hybrid model for nodes

### ISSUE THREAD

**Issue by mmd-osm** [osmlab/osm-data-model#1]
This is something we already discussed via email, just putting it here so it doesn't get lost. It's a follow up for [1].

Some general remarks:

* Lat/lon coordinates typically need 64 bits to be stored. However, for the whole planet in the range (-90, -180) --> (90, 180), only 63 bits are effectively needed, leaving one bit for other purposes. 
* lat/lon values can be stored as interleaved bits, like implemented for Overpass API [2].

Based on this we could move a node which is only referenced by a single node, and doesn't have any tags on its own, directly into a way (as way member).

To mark such a node to represent a coordinate rather than an actual node id, the highest bit 64 is set to "1". In other cases, where a way member still references an actual node id, the highest bit is set to "0".

Based on this approach, I did some analysis [3] on a planet file to evaluate potential savings:

Stats for planet-180402.osm.pbf

Object type | Number of objects  | Comments
-------------|----------------------:|---------
Nodes      | 4'421'656'855       |     (includes nodes without way reference)
Ways  | 481'949'093   |
Relations | 5'715'146  |

Distinct node ids, which are used in ways as a way member: 4'350'125'688

Now applying the approach outlined above, i.e. moving nodes without tags which are only used in a single way, we can split the 4.35 billion nodes above into two groups:

* Vertices: 3'792'988'045         (used to be a node, now a coordinate in a way)
* Retained Nodes: 557'137'643    (Node is still kept as individual node)

This means that for all 4.3 billion nodes currently referenced by ways, 3.8 billion nodes could be deleted right away and moved as coordinate into a way. Node members in ways already have 64 bit size, and we're just re-using this space to carry lat/lon information, rather than reference a node id.

For a specialized planet, **85% of all nodes, including metadata could be removed**, i.e. only 580 million nodes are left which are either used by multiple ways and/or have their own tag.

All of today's topological characteristics would still be available. This could be an evolutionary step to still use the current data model, while radically reducing the number of node ids.

What are the side effects?

* We would be losing the meta data for vertices that only carry some lat/lon details for a way
* Changing the location of such a coordinate way member creates a new way version. Before, it would only create a new node version. This can cause a huge data volume, if each way's version is kept as a full snapshot (like in today's API data model).
* Turning a vertex into a node and vice versa needs special editor support (if we apply this concept to the main OSM data model).
* Way members' node ids have the foreign key relationship to the node table. This won't work anymore, if a way member id represents a lat/lon value, rather than a node id. This may be more of an issue when applying this model to the main OSM DB, rather than some specialized planet (which doesn't require referential constraints per se).

---

Links:

[1] https://media.ccc.de/v/2018-5412-evolution_des_openstreetmap-datenmodells

[2] https://github.com/drolbr/Overpass-API/blob/master/src/overpass_api/core/index_computations.h

[3] https://github.com/mmd-osm/libosmium/blob/vertex/examples/osmium_vertex.cpp

**Comment by mmd-osm** [comment]
Now that we’re reaching 6 billion nodes, it may be a good time to revisit 

By the way, @simonpoole: 99% savings is probably really really optimistic and not backed by any serious analysis: https://mobile.twitter.com/sp8962/status/1259467407632015364

**Comment by simonpoole** [comment]
Spoilsport :-)

PS given that OSM is now really OBM I would actually expect the percentage to have gone up.

**Comment by mmd-osm** [comment]
I’m only very slight worried that people don’t get your irony and base their decision making process on insights they’ve gained on Twitter. I guess you know what I mean.
