### ISSUE TITLE
What's the status?

### ISSUE THREAD

**Issue by flowrean** [osmlab/osm-data-model#5]
Hi,
I just saw the talk from State of the Map 2018 and I have become quite interested, but it seems this project died soon after it was started. Or is it still being worked on? Is there any perspective on an update to the OSM data model?

**Comment by joto** [comment]
It seems nobody had the time and/or energy to work on this.

**Comment by mmd-osm** [comment]
[EWG](https://wiki.osmfoundation.org/wiki/Engineering_Working_Group) seems to take care of the topic now. It's still a bit light on details, though.

https://wiki.osmfoundation.org/wiki/Working_Group_Minutes/EWG_2022-01-24#OSM_data_model_changes

**Comment by RobJN** [comment]
Status update:

>The [OSMF Engineering Working Group (EWG)](https://wiki.osmfoundation.org/wiki/Engineering_Working_Group) has commissioned me (Jochen Topf) to write a study over the next months outlining the problems with our current data model, possible improvements and their impact on our systems.

https://blog.openstreetmap.org/2022/06/02/announcement-data-model-study/

**Comment by joto** [comment]
I encourage everybody to [read the study](https://media.jochentopf.com/media/2022-08-15-study-evolution-of-the-osm-data-model.pdf) and joint the [discussions](https://github.com/osmlab/osm-data-model/discussions).
